package com.wavechat.component;

public class ChatHeader extends javax.swing.JPanel {

    public ChatHeader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        leftContainer = new javax.swing.JPanel();
        userAvatar1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        onlineLabel = new javax.swing.JLabel();
        rightContainer = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        moreButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 73));
        setLayout(new java.awt.GridBagLayout());

        leftContainer.setPreferredSize(new java.awt.Dimension(200, 70));

        userAvatar1.setText("Avatar1");
        userAvatar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userAvatar1.setPreferredSize(new java.awt.Dimension(54, 54));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setText("User1");

        onlineLabel.setText("Online");

        javax.swing.GroupLayout leftContainerLayout = new javax.swing.GroupLayout(leftContainer);
        leftContainer.setLayout(leftContainerLayout);
        leftContainerLayout.setHorizontalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        leftContainerLayout.setVerticalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineLabel))
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(leftContainer, gridBagConstraints);

        rightContainer.setMinimumSize(new java.awt.Dimension(0, 0));
        rightContainer.setPreferredSize(new java.awt.Dimension(294, 32));
        rightContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));

        searchButton.setBackground(new java.awt.Color(26, 41, 128));
        searchButton.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setPreferredSize(new java.awt.Dimension(68, 32));
        rightContainer.add(searchButton);

        moreButton.setBackground(new java.awt.Color(26, 41, 128));
        moreButton.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        moreButton.setForeground(new java.awt.Color(255, 255, 255));
        moreButton.setText("More");
        moreButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        moreButton.setPreferredSize(new java.awt.Dimension(68, 32));
        rightContainer.add(moreButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 301;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 6);
        add(rightContainer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftContainer;
    private javax.swing.JButton moreButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel onlineLabel;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel userAvatar1;
    // End of variables declaration//GEN-END:variables
}
