package com.wavechat.component;

import com.wavechat.bus.GroupChatBUS;
import com.wavechat.dto.FriendDTO;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class FriendPanel extends javax.swing.JPanel {
    private FriendDTO friendDTO;
    private int groupID;
    private ChatHeader chatHeader;
    
    public FriendPanel(FriendDTO friendDTO, int groupID, ChatHeader chatHeader) {
        initComponents();
        
        this.friendDTO = friendDTO;
        this.groupID = groupID;
        this.chatHeader = chatHeader;
        
        fullNameLabel.setText(friendDTO.getFullName());
        userNameLabel.setText(friendDTO.getUserName());
    }
    
    public void addAddMemberButtonListener() {
        // Loại bỏ tất cả ActionListener (nếu có)
        for (ActionListener listener : addButton.getActionListeners()) {
                   addButton.removeActionListener(listener); // Loại bỏ tất cả listener cũ
        }
        addButton.addActionListener(evt -> handleAddMember());
    }
        
    private void handleAddMember() {
        // Tạo một instance của GroupChatBUS
        GroupChatBUS groupChatBUS = new GroupChatBUS();

        // Gọi hàm addMember với thông tin cần thiết
        boolean isAdded = groupChatBUS.addMember(friendDTO.getUserID(), groupID, false);

        if (isAdded) {
            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Member added successfully: " + friendDTO.getFullName(), "Success", JOptionPane.INFORMATION_MESSAGE);

            // Update UI
            java.awt.Window dialog = SwingUtilities.getWindowAncestor(this);
            if (dialog instanceof JDialog) {
                ((JDialog) dialog).dispose();
            }
                
            chatHeader.openFriendListPanel(groupID);
        } else {
            // Hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Failed to add member. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userAvatar = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(0, 75));
        setPreferredSize(new java.awt.Dimension(690, 75));

        userAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        userAvatar.setText("Avatar1");
        userAvatar.setPreferredSize(new java.awt.Dimension(54, 54));

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        userNameLabel.setText(" ");

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullNameLabel.setText(" ");

        addButton.setBackground(new java.awt.Color(26, 41, 128));
        addButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add to group");
        addButton.setMaximumSize(new java.awt.Dimension(144, 40));
        addButton.setMinimumSize(new java.awt.Dimension(144, 40));
        addButton.setPreferredSize(new java.awt.Dimension(144, 40));
        buttonContainer.add(addButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fullNameLabel)
                        .addGap(10, 10, 10)
                        .addComponent(userNameLabel))
                    .addComponent(userAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel userAvatar;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
