package com.wavechat.component;

public class RightMessage extends javax.swing.JLayeredPane {

    public RightMessage() {
        initComponents();
    }
    
    public void setRightMessage(String msg) {
        message.setMessage(msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new com.wavechat.component.Message();

        setBackground(new java.awt.Color(102, 204, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(message);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wavechat.component.Message message;
    // End of variables declaration//GEN-END:variables
}
