package com.wavechat.component;

import com.wavechat.bus.ConversationBUS;
import com.wavechat.dto.ConversationDTO;
import com.wavechat.dto.UserDTO;
import com.wavechat.form.UserHomeMain;
import javax.swing.SwingUtilities;

public class UserSearchPanel extends javax.swing.JPanel {

    public UserSearchPanel(UserDTO userDTO) {
        initComponents();
        
        fullNameLabel.setText(userDTO.getFullName());
        userNameLabel.setText(userDTO.getUserName());
    }
    
    public void addAddFriendButton() {
        buttonContainer.add(addFriendButton);
        buttonContainer.revalidate();
        buttonContainer.repaint();
    }
    
    public void addCreateGroupButton() {
        buttonContainer.add(createGroupButton);
        buttonContainer.revalidate();
        buttonContainer.repaint();
    }
    
    // Gán sự kiện cho nút Chat
    public void addChatButtonListener(String friendID) {
        chatButton.addActionListener(evt -> onChatButtonClicked(friendID));
    }

    // Gán sự kiện cho nút Add Friend
    public void addAddFriendButtonListener(String friendID) {
        addFriendButton.addActionListener(evt -> onAddFriendButtonClicked(friendID));
    }

    // Gán sự kiện cho nút Create Group
    public void addCreateGroupButtonListener(String friendID) {
        createGroupButton.addActionListener(evt -> onCreateGroupButtonClicked(friendID));
    }
    
    private void onChatButtonClicked(String friendID) {                                           
        System.out.println("Chat with " + friendID);
        handleChat(friendID);
    }                                          

    private void onAddFriendButtonClicked(String friendID) {                                                
        System.out.println("Add friend " + friendID);
    }                                               

    private void onCreateGroupButtonClicked(String friendID) {                                                  
        System.out.println("Create group with " + friendID);
    }  
    
    private void handleChat(String friendID) {
        // Tạo conversation nếu chưa có
        ConversationBUS conversationBUS = new ConversationBUS();
        // Kiểm tra xem conversation đã tồn tại giữa currentUserID và friendID chưa
        ConversationDTO conversationDTO = conversationBUS.checkConversationExists(friendID);

        if (conversationDTO == null) {
            // Nếu không tồn tại conversation, tạo 1 cái mới
            conversationDTO = conversationBUS.addConversation(friendID);
        }
        
        // Mở chat
        UserHomeMain userHomeMain = (UserHomeMain) SwingUtilities.getWindowAncestor(this);  // Lấy tham chiếu đến UserHomeMain
        userHomeMain.showChatPanel();  
        userHomeMain.userHomePanel.openConversation(conversationDTO);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFriendButton = new javax.swing.JButton();
        createGroupButton = new javax.swing.JButton();
        userAvatar = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JPanel();
        chatButton = new javax.swing.JButton();

        addFriendButton.setBackground(new java.awt.Color(26, 41, 128));
        addFriendButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        addFriendButton.setForeground(new java.awt.Color(255, 255, 255));
        addFriendButton.setText("Add friend");
        addFriendButton.setMaximumSize(new java.awt.Dimension(144, 40));
        addFriendButton.setMinimumSize(new java.awt.Dimension(144, 40));
        addFriendButton.setPreferredSize(new java.awt.Dimension(144, 40));

        createGroupButton.setBackground(new java.awt.Color(26, 41, 128));
        createGroupButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        createGroupButton.setForeground(new java.awt.Color(255, 255, 255));
        createGroupButton.setText("Create group");
        createGroupButton.setMaximumSize(new java.awt.Dimension(144, 40));
        createGroupButton.setMinimumSize(new java.awt.Dimension(144, 40));
        createGroupButton.setPreferredSize(new java.awt.Dimension(144, 40));

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1300, 75));

        userAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        userAvatar.setText("Avatar1");
        userAvatar.setPreferredSize(new java.awt.Dimension(54, 54));

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullNameLabel.setText(" ");

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        userNameLabel.setText(" ");

        chatButton.setBackground(new java.awt.Color(26, 41, 128));
        chatButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        chatButton.setForeground(new java.awt.Color(255, 255, 255));
        chatButton.setText("Chat");
        chatButton.setMaximumSize(new java.awt.Dimension(144, 40));
        chatButton.setMinimumSize(new java.awt.Dimension(144, 40));
        chatButton.setPreferredSize(new java.awt.Dimension(144, 40));
        buttonContainer.add(chatButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(fullNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel))
                        .addComponent(userAvatar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriendButton;
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JButton chatButton;
    private javax.swing.JButton createGroupButton;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel userAvatar;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
