/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wavechat.contentPanel;

import com.wavechat.bus.UserBUS;
import com.wavechat.dto.UserDTO;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author buihi
 */
public class AdminUserPanel_NewRegister extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    /**
     * Creates new form AdminUserPanel_NewRegister
     */
    public AdminUserPanel_NewRegister() {
        initComponents();
        
        tableModel = new DefaultTableModel(new Object[]{"Username", "Name", "Email","Day Created"}, 0);
        newRegisterTable.setModel(tableModel);
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tableModel);
        newRegisterTable.setRowSorter(sorter);
    }
    
    public boolean isDateInRange(Date dateFrom, Date dateTo, Date createdDate) {
        // Kiểm tra nếu createdDate nằm trong khoảng từ dateFrom đến dateTo
        return (createdDate.equals(dateFrom) || createdDate.after(dateFrom)) && 
               (createdDate.equals(dateTo) || createdDate.before(dateTo));
    }
    
    public void updateTable() {
        tableModel.setRowCount(0);
        Date dateFrom = jDateFrom.getDate();
        Date dateTo = jDateTo.getDate();
        UserBUS userBUS = new UserBUS();
        List<UserDTO> userList = userBUS.getAll();

        if (dateFrom == null || dateTo == null){
            for (UserDTO user : userList) {
                tableModel.addRow(new Object[]{
                    user.getUserName(), 
                    user.getFullName(),       
                    user.getEmail(),
                    user.getCreatedDate(),
                });
            }
        }
        else {
            for (UserDTO user : userList) {
                Date createdDate = user.getCreatedDate();
                if (isDateInRange(dateFrom, dateTo, createdDate)) { 
                    tableModel.addRow(new Object[]{
                        user.getUserName(), 
                        user.getFullName(),       
                        user.getEmail(),
                        user.getCreatedDate(),
                    });
                }
            }
        }
    }
    
    private void applyFilter() {
        String searchName = filterName.getText(); 
        String searchEmail = filterEmail.getText(); 

        // Xử lý bộ lọc
        DefaultTableModel dtm = (DefaultTableModel) newRegisterTable.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<>(dtm);
        newRegisterTable.setRowSorter(sorter);

        List<RowFilter<TableModel, Object>> filters = new ArrayList<>();

        if (!searchName.isEmpty()) {
            RowFilter<TableModel, Object> nameFilter = RowFilter.regexFilter("(?i)" + searchName, 0, 1);
            filters.add(nameFilter);
        }

        if (!searchEmail.isEmpty()) {
            RowFilter<TableModel, Object> emailFilter = RowFilter.regexFilter("(?i)" + searchEmail, 2);
            filters.add(emailFilter);
        }

        if (!filters.isEmpty()) {
            sorter.setRowFilter(RowFilter.andFilter(filters));
        } else {
            sorter.setRowFilter(null); // Không áp dụng bộ lọc nếu tất cả trống
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jButtonUpdateTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newRegisterTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        filterName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filterEmail = new javax.swing.JTextField();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("FROM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("TO");

        jButtonUpdateTable.setText("Update table");
        jButtonUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonUpdateTable)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpdateTable)
                    .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jDateTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jScrollPane1.setViewportView(newRegisterTable);

        jLabel2.setText("Search by name:");

        filterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterNameActionPerformed(evt);
            }
        });
        filterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterNameKeyReleased(evt);
            }
        });

        jLabel3.setText("Search by email:");

        filterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterEmailActionPerformed(evt);
            }
        });
        filterEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterEmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(filterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterNameActionPerformed

    private void filterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterEmailActionPerformed

    private void filterNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterNameKeyReleased
        // TODO add your handling code here:
        applyFilter();
    }//GEN-LAST:event_filterNameKeyReleased

    private void filterEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterEmailKeyReleased
        // TODO add your handling code here:
        applyFilter();
    }//GEN-LAST:event_filterEmailKeyReleased

    private void jButtonUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTableActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_jButtonUpdateTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filterEmail;
    private javax.swing.JTextField filterName;
    private javax.swing.JButton jButtonUpdateTable;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newRegisterTable;
    // End of variables declaration//GEN-END:variables
}
