package com.wavechat.contentPanel;

import com.wavechat.form.AuthenticationMain;

public class AuthenticationThankYouPanel extends javax.swing.JPanel {

    public AuthenticationThankYouPanel() {
        initComponents();
    }
    
    private AuthenticationMain parentFrame;

    // Constructor nhận tham chiếu đến AuthenticationMain
    public AuthenticationThankYouPanel(AuthenticationMain parent) {
        initComponents();
        this.parentFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        thankyou = new java.awt.Panel();
        thankyouContainer = new java.awt.Panel();
        logo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        forgotpassButton1 = new javax.swing.JPanel();
        description = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        or = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        checkemail = new javax.swing.JPanel();
        jTextArea3 = new javax.swing.JTextArea();
        loginButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        thankyou.setBackground(new java.awt.Color(246, 246, 246));
        thankyou.setPreferredSize(new java.awt.Dimension(500, 600));
        thankyou.setLayout(new java.awt.GridBagLayout());

        thankyouContainer.setBackground(new java.awt.Color(246, 246, 246));
        thankyouContainer.setLayout(new java.awt.GridBagLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        thankyouContainer.add(logo, gridBagConstraints);

        login.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        login.setText("Thank you");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        thankyouContainer.add(login, gridBagConstraints);

        forgotpassButton1.setBackground(new java.awt.Color(246, 246, 246));
        forgotpassButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        thankyouContainer.add(forgotpassButton1, gridBagConstraints);

        description.setBackground(new java.awt.Color(246, 246, 246));
        description.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jTextArea2.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea2.setColumns(5);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(3);
        jTextArea2.setText("We've sent a confirmation email to your address. Please check your email and click the confirmation link to reset your password.");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jTextArea2.setPreferredSize(new java.awt.Dimension(280, 52));
        description.add(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        thankyouContainer.add(description, gridBagConstraints);

        or.setBackground(new java.awt.Color(246, 246, 246));
        or.setPreferredSize(new java.awt.Dimension(294, 24));
        or.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 1));
        or.add(jPanel1);

        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(1);
        jTextArea1.setTabSize(1);
        jTextArea1.setText("or");
        jTextArea1.setToolTipText("");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextArea1.setPreferredSize(new java.awt.Dimension(30, 12));
        or.add(jTextArea1);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 1));
        or.add(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        thankyouContainer.add(or, gridBagConstraints);

        checkemail.setBackground(new java.awt.Color(246, 246, 246));
        checkemail.setPreferredSize(new java.awt.Dimension(280, 36));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        checkemail.setLayout(flowLayout1);

        jTextArea3.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea3.setColumns(3);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(2);
        jTextArea3.setText("Haven’t received the email? Please check on Spam or Promotions.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        jTextArea3.setPreferredSize(new java.awt.Dimension(250, 52));
        checkemail.add(jTextArea3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        thankyouContainer.add(checkemail, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(26, 41, 128));
        loginButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Resend email");
        loginButton.setPreferredSize(new java.awt.Dimension(294, 35));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 35, 0);
        thankyouContainer.add(loginButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 98, 101);
        thankyou.add(thankyouContainer, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(26, 41, 128));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_white.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        thankyou.add(jButton1, gridBagConstraints);

        add(thankyou, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        parentFrame.showLoginPanel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel checkemail;
    private javax.swing.JPanel description;
    private javax.swing.JPanel forgotpassButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel or;
    private java.awt.Panel thankyou;
    private java.awt.Panel thankyouContainer;
    // End of variables declaration//GEN-END:variables
}
