package com.wavechat.contentPanel;

import com.wavechat.bus.UserBUS;
import com.wavechat.form.AuthenticationMain;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class AuthenticationRegisterPanel extends javax.swing.JPanel {

    public AuthenticationRegisterPanel() {
        initComponents();
    }
    
    private void handleRegister() {
        String userName = usernameInput.getText();
        String email = emailInput.getText();
        char[] passwordChar = passwordInput.getPassword();
        String password = new String(passwordChar); 
        char[] confirmPasswordChar = confirmPasswordInput.getPassword();
        String confirmPassword = new String(confirmPasswordChar); 

        UserBUS userBUS = new UserBUS(); 
        // Kiểm tra các trường đầu vào
        if (userName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill full information!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra xem tên người dùng và email đã tồn tại chưa
        if (userBUS.isUserNameExist(userName)) {
            JOptionPane.showMessageDialog(this, "Username existed!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!userBUS.isEmailValid(email)) {
            JOptionPane.showMessageDialog(this, "Email is not valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (userBUS.isEmailExist(email)) {
            JOptionPane.showMessageDialog(this, "Email existed!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!userBUS.isPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, "Password must have at least 8 characters, including 1 uppercase letter, 1 lowercase letter, and 1 number!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!confirmPassword.equals(password)) {
            JOptionPane.showMessageDialog(this, "Password and confirm password do not match.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = userBUS.addNewUser(userName, email, password);

        if (success) {
            // Hiển thị thông báo đăng ký thành công và nút quay lại đăng nhập
            int option = JOptionPane.showOptionDialog(this,
                    "Register successful!",
                    "successful",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    new Object[] { "Back to login" }, "Back to login");

            // Nếu người dùng nhấn "Quay lại đăng nhập"
            if (option == 0) {
                // Navigate qua login
                parentFrame.showLoginPanel();
            }
        } else {
            JOptionPane.showMessageDialog(this, "There is error when register. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private AuthenticationMain parentFrame;

    // Constructor nhận tham chiếu đến AuthenticationMain
    public AuthenticationRegisterPanel(AuthenticationMain parent) {
        initComponents();
        this.parentFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new java.awt.Panel();
        loginContainer = new java.awt.Panel();
        logo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        usernameInput = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        donothaveacc = new javax.swing.JLabel();
        navLoginButton = new javax.swing.JButton();
        confirmPasswordInput = new javax.swing.JPasswordField();
        passwordInput = new javax.swing.JPasswordField();
        showPassButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        register.setBackground(new java.awt.Color(246, 246, 246));
        register.setPreferredSize(new java.awt.Dimension(500, 600));
        register.setLayout(new java.awt.GridBagLayout());

        loginContainer.setBackground(new java.awt.Color(246, 246, 246));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        login.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        login.setText("Register");

        slogan.setText("Join to connect and share your waves.");

        emailInput.setBackground(new java.awt.Color(246, 246, 246));
        emailInput.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        emailInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        emailInput.setPreferredSize(new java.awt.Dimension(294, 35));

        usernameInput.setBackground(new java.awt.Color(246, 246, 246));
        usernameInput.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        usernameInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        usernameInput.setPreferredSize(new java.awt.Dimension(294, 35));

        registerButton.setBackground(new java.awt.Color(26, 41, 128));
        registerButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setPreferredSize(new java.awt.Dimension(294, 35));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        donothaveacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        donothaveacc.setText("Already have an account?");

        navLoginButton.setBackground(new java.awt.Color(26, 41, 128));
        navLoginButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        navLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        navLoginButton.setText("Login");
        navLoginButton.setPreferredSize(new java.awt.Dimension(100, 35));
        navLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLoginButtonActionPerformed(evt);
            }
        });

        confirmPasswordInput.setBackground(new java.awt.Color(246, 246, 246));
        confirmPasswordInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirm password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 0, 12))); // NOI18N
        confirmPasswordInput.setPreferredSize(new java.awt.Dimension(294, 35));
        confirmPasswordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmPasswordInputKeyPressed(evt);
            }
        });

        passwordInput.setBackground(new java.awt.Color(246, 246, 246));
        passwordInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 0, 12))); // NOI18N
        passwordInput.setPreferredSize(new java.awt.Dimension(294, 35));

        showPassButton.setBackground(new java.awt.Color(26, 41, 128));
        showPassButton.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        showPassButton.setForeground(new java.awt.Color(255, 255, 255));
        showPassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notshow.png"))); // NOI18N
        showPassButton.setPreferredSize(new java.awt.Dimension(40, 40));
        showPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(logo))
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(login))
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(slogan))
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(donothaveacc))
                    .addComponent(navLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(loginContainerLayout.createSequentialGroup()
                            .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(showPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(10, 10, 10)
                .addComponent(login)
                .addGap(5, 5, 5)
                .addComponent(slogan)
                .addGap(10, 10, 10)
                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(donothaveacc)
                .addGap(10, 10, 10)
                .addComponent(navLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        register.add(loginContainer, new java.awt.GridBagConstraints());

        add(register, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        handleRegister();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void navLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLoginButtonActionPerformed
        parentFrame.showLoginPanel();
    }//GEN-LAST:event_navLoginButtonActionPerformed

    private void showPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassButtonActionPerformed
        if ("show".equals(mode)){
            passwordInput.setEchoChar('•');
            confirmPasswordInput.setEchoChar('•');
            showPassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notshow.png")));
            mode = "notshow";
        }
        else {
            passwordInput.setEchoChar('\0');
            confirmPasswordInput.setEchoChar('\0');
            showPassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            mode = "show";
        }
    }//GEN-LAST:event_showPassButtonActionPerformed

    private void confirmPasswordInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordInputKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            handleRegister();
        }
    }//GEN-LAST:event_confirmPasswordInputKeyPressed

    private String mode = "notshow";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordInput;
    private javax.swing.JLabel donothaveacc;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel login;
    private java.awt.Panel loginContainer;
    private javax.swing.JLabel logo;
    private javax.swing.JButton navLoginButton;
    private javax.swing.JPasswordField passwordInput;
    private java.awt.Panel register;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showPassButton;
    private javax.swing.JLabel slogan;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
