package com.wavechat.contentPanel;

import com.wavechat.bus.UserBUS;
import com.wavechat.form.AuthenticationMain;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class AuthenticationForgotPassPanel extends javax.swing.JPanel {

    public AuthenticationForgotPassPanel() {
        initComponents();
    }
    
    private AuthenticationMain parentFrame;

    // Constructor nhận tham chiếu đến AuthenticationMain
    public AuthenticationForgotPassPanel(AuthenticationMain parent) {
        initComponents();
        this.parentFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        forgotpass = new java.awt.Panel();
        backButton = new javax.swing.JButton();
        forgotPassContainer = new java.awt.Panel();
        logo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        forgotpassButton1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        emailInput = new javax.swing.JTextField();
        resetPasswordButton = new javax.swing.JButton();
        forgotpassButton = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        forgotpass.setBackground(new java.awt.Color(246, 246, 246));
        forgotpass.setPreferredSize(new java.awt.Dimension(500, 600));

        backButton.setBackground(new java.awt.Color(26, 41, 128));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_white.png"))); // NOI18N
        backButton.setPreferredSize(new java.awt.Dimension(40, 40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        forgotPassContainer.setBackground(new java.awt.Color(246, 246, 246));
        forgotPassContainer.setLayout(new java.awt.GridBagLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        forgotPassContainer.add(logo, gridBagConstraints);

        login.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        login.setText("Forgot password?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        forgotPassContainer.add(login, gridBagConstraints);

        forgotpassButton1.setBackground(new java.awt.Color(246, 246, 246));
        forgotpassButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jTextArea1.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Don't worry! Please enter the email address linked to your account to reset your password.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.setPreferredSize(new java.awt.Dimension(320, 36));
        forgotpassButton1.add(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        forgotPassContainer.add(forgotpassButton1, gridBagConstraints);

        emailInput.setBackground(new java.awt.Color(246, 246, 246));
        emailInput.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        emailInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        emailInput.setPreferredSize(new java.awt.Dimension(294, 35));
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        forgotPassContainer.add(emailInput, gridBagConstraints);

        resetPasswordButton.setBackground(new java.awt.Color(26, 41, 128));
        resetPasswordButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        resetPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        resetPasswordButton.setLabel("Send email");
        resetPasswordButton.setPreferredSize(new java.awt.Dimension(294, 35));
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });
        resetPasswordButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetPasswordButtonKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 35, 0);
        forgotPassContainer.add(resetPasswordButton, gridBagConstraints);

        forgotpassButton.setBackground(new java.awt.Color(246, 246, 246));
        forgotpassButton.setPreferredSize(new java.awt.Dimension(200, 22));
        forgotpassButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        forgotPassContainer.add(forgotpassButton, gridBagConstraints);

        javax.swing.GroupLayout forgotpassLayout = new javax.swing.GroupLayout(forgotpass);
        forgotpass.setLayout(forgotpassLayout);
        forgotpassLayout.setHorizontalGroup(
            forgotpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpassLayout.createSequentialGroup()
                .addGroup(forgotpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotpassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotpassLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(forgotPassContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        forgotpassLayout.setVerticalGroup(
            forgotpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotpassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(forgotPassContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(forgotpass, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        String email = emailInput.getText();
        UserBUS userBUS = new UserBUS();
        if(userBUS.resetPassword(email)) {
            // Reset thành công
            parentFrame.showThankYouPanel();
        }
        else {
            JOptionPane.showMessageDialog(this, "There is error when reset password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parentFrame.showLoginPanel();
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetPasswordButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetPasswordButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String email = emailInput.getText();
            UserBUS userBUS = new UserBUS();
            if(userBUS.resetPassword(email)) {
                // Reset thành công
                parentFrame.showThankYouPanel();
            }
            else {
                JOptionPane.showMessageDialog(this, "There is error when reset password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_resetPasswordButtonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailInput;
    private java.awt.Panel forgotPassContainer;
    private java.awt.Panel forgotpass;
    private javax.swing.JPanel forgotpassButton;
    private javax.swing.JPanel forgotpassButton1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel logo;
    private javax.swing.JButton resetPasswordButton;
    // End of variables declaration//GEN-END:variables
}
