package com.wavechat.contentPanel;

import com.wavechat.GlobalVariable;
import com.wavechat.bus.UserBUS;
import com.wavechat.component.UserSearchPanel;
import com.wavechat.dto.UserDTO;
import java.util.ArrayList;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class UserFindFriendPanel extends javax.swing.JPanel {
    private int offset = 0;
    private int limit = 5;
    
    public UserFindFriendPanel() {
        initComponents();
        resultPanel.setLayout(new MigLayout("fillx"));
    }

    public void resetOffet() {
        this.offset = 0;
    }
    
    private void handleSearch() {
        String query = searchInput.getText();
        String selectedChoice = (String) searchChoice.getSelectedItem();
        UserBUS userBUS = new UserBUS();

        List<UserDTO> findedUsers = new ArrayList<>();
        if ("Username".equals(selectedChoice)) {
            findedUsers = userBUS.findUserByUserName(query, offset, limit);
        } else if ("Fullname".equals(selectedChoice)) {
            findedUsers = userBUS.findUserByFullName(query, offset, limit);
        }
        
        // Hiển thị thêm người dùng
        for (UserDTO user : findedUsers) {
            UserSearchPanel userPanel = new UserSearchPanel(user);
            userPanel.addChatButtonListener(user.getUserID());
            
            if (!userBUS.isFriend(GlobalVariable.getUserID(), user.getUserID())) {
                userPanel.addAddFriendButton();
                userPanel.addAddFriendButtonListener(user.getUserID());
            }
            else {
                userPanel.addCreateGroupButton();
                userPanel.addCreateGroupButtonListener(user.getUserID());
            }
            
            resultPanel.add(userPanel, "wrap, w ::100%");
        }
        
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findFriendLabel = new javax.swing.JLabel();
        contentContainer = new javax.swing.JPanel();
        searchBarContainer = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchChoice = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultPanel = new javax.swing.JPanel();
        buttonContainer = new javax.swing.JPanel();
        loadMoreButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(741, 600));

        findFriendLabel.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        findFriendLabel.setText("Find Friend");
        findFriendLabel.setPreferredSize(new java.awt.Dimension(214, 32));

        contentContainer.setPreferredSize(new java.awt.Dimension(726, 700));
        contentContainer.setLayout(new java.awt.BorderLayout());

        searchBarContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchInput.setText("Search username");
        searchInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 0));
        searchInput.setPreferredSize(new java.awt.Dimension(642, 38));
        searchInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInputMouseClicked(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(26, 41, 128));
        searchButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setBorder(null);
        searchButton.setPreferredSize(new java.awt.Dimension(80, 38));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Username", "Fullname" }));

        javax.swing.GroupLayout searchBarContainerLayout = new javax.swing.GroupLayout(searchBarContainer);
        searchBarContainer.setLayout(searchBarContainerLayout);
        searchBarContainerLayout.setHorizontalGroup(
            searchBarContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarContainerLayout.createSequentialGroup()
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(searchChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        searchBarContainerLayout.setVerticalGroup(
            searchBarContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(searchBarContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentContainer.add(searchBarContainer, java.awt.BorderLayout.PAGE_START);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(726, 472));

        resultPanel.setPreferredSize(new java.awt.Dimension(686, 688));
        resultPanel.setLayout(new javax.swing.BoxLayout(resultPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane4.setViewportView(resultPanel);

        contentContainer.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        buttonContainer.setPreferredSize(new java.awt.Dimension(720, 33));
        buttonContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        loadMoreButton.setBackground(new java.awt.Color(26, 41, 128));
        loadMoreButton.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        loadMoreButton.setForeground(new java.awt.Color(255, 255, 255));
        loadMoreButton.setText("Find more");
        loadMoreButton.setMaximumSize(new java.awt.Dimension(120, 30));
        loadMoreButton.setMinimumSize(new java.awt.Dimension(120, 30));
        loadMoreButton.setPreferredSize(new java.awt.Dimension(120, 30));
        loadMoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMoreButtonActionPerformed(evt);
            }
        });
        buttonContainer.add(loadMoreButton);

        contentContainer.add(buttonContainer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contentContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addComponent(findFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        resultPanel.removeAll();
        resetOffet();
        handleSearch();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInputMouseClicked
        searchInput.setText("");
    }//GEN-LAST:event_searchInputMouseClicked

    private void loadMoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMoreButtonActionPerformed
        offset += limit;
        handleSearch();
    }//GEN-LAST:event_loadMoreButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JPanel contentContainer;
    private javax.swing.JLabel findFriendLabel;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton loadMoreButton;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel searchBarContainer;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchChoice;
    private javax.swing.JTextField searchInput;
    // End of variables declaration//GEN-END:variables
}
