/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wavechat.form;

/**
 *
 * @author buihi
 */
public class AdminUser_Friends extends javax.swing.JFrame {

    /**
     * Creates new form AdmainUser_Friends
     */
    public AdminUser_Friends() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        notiButton = new javax.swing.JButton();
        usetModeButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        menuUserBar = new javax.swing.JPanel();
        allUser7 = new javax.swing.JLabel();
        newRegister4 = new javax.swing.JLabel();
        activityLog4 = new javax.swing.JLabel();
        inSig4 = new javax.swing.JLabel();
        allUser8 = new javax.swing.JLabel();
        navContainer1 = new javax.swing.JPanel();
        dashboardNav1 = new javax.swing.JButton();
        userNav = new javax.swing.JButton();
        groupchatNav = new javax.swing.JButton();
        spamReportNav = new javax.swing.JButton();
        loginHistoryNav = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setPreferredSize(new java.awt.Dimension(178, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N
        jLabel2.setText("WAVE");

        notiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        notiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiButtonActionPerformed(evt);
            }
        });

        usetModeButton.setText("User mode");
        usetModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usetModeButtonActionPerformed(evt);
            }
        });

        userButton.setText("User");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                .addComponent(notiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(usetModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(usetModeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuUserBar.setBorder(new javax.swing.border.MatteBorder(null));

        allUser7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        allUser7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allUser7.setText("Friends");
        allUser7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        newRegister4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newRegister4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newRegister4.setText("New register");
        newRegister4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        activityLog4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activityLog4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityLog4.setText("Activity Log");
        activityLog4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        inSig4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inSig4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inSig4.setText("Insight");
        inSig4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        allUser8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allUser8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allUser8.setText("All User");
        allUser8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout menuUserBarLayout = new javax.swing.GroupLayout(menuUserBar);
        menuUserBar.setLayout(menuUserBarLayout);
        menuUserBarLayout.setHorizontalGroup(
            menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUserBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(allUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRegister4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityLog4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inSig4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuUserBarLayout.setVerticalGroup(
            menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUserBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSig4)
                    .addComponent(activityLog4)
                    .addComponent(newRegister4)
                    .addComponent(allUser7)
                    .addComponent(allUser8))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        navContainer1.setBorder(new javax.swing.border.MatteBorder(null));
        navContainer1.setPreferredSize(new java.awt.Dimension(188, 496));

        dashboardNav1.setBackground(new java.awt.Color(26, 41, 128));
        dashboardNav1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboardNav1.setForeground(new java.awt.Color(255, 255, 255));
        dashboardNav1.setText("Dashboard");
        dashboardNav1.setPreferredSize(new java.awt.Dimension(165, 40));
        dashboardNav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNav1ActionPerformed(evt);
            }
        });

        userNav.setBackground(new java.awt.Color(26, 41, 128));
        userNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userNav.setForeground(new java.awt.Color(255, 255, 255));
        userNav.setText("User");
        userNav.setMaximumSize(new java.awt.Dimension(165, 40));
        userNav.setMinimumSize(new java.awt.Dimension(165, 40));
        userNav.setPreferredSize(new java.awt.Dimension(165, 40));
        userNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNavActionPerformed(evt);
            }
        });

        groupchatNav.setBackground(new java.awt.Color(26, 41, 128));
        groupchatNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        groupchatNav.setForeground(new java.awt.Color(255, 255, 255));
        groupchatNav.setText("Login History");
        groupchatNav.setPreferredSize(new java.awt.Dimension(165, 40));

        spamReportNav.setBackground(new java.awt.Color(26, 41, 128));
        spamReportNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spamReportNav.setForeground(new java.awt.Color(255, 255, 255));
        spamReportNav.setText("Spam Report");
        spamReportNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spamReportNavActionPerformed(evt);
            }
        });

        loginHistoryNav.setBackground(new java.awt.Color(26, 41, 128));
        loginHistoryNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginHistoryNav.setForeground(new java.awt.Color(255, 255, 255));
        loginHistoryNav.setText("Group Chat");

        javax.swing.GroupLayout navContainer1Layout = new javax.swing.GroupLayout(navContainer1);
        navContainer1.setLayout(navContainer1Layout);
        navContainer1Layout.setHorizontalGroup(
            navContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardNav1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(userNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupchatNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginHistoryNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spamReportNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navContainer1Layout.setVerticalGroup(
            navContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navContainer1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(dashboardNav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupchatNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginHistoryNav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spamReportNav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nguyenvana",  new Integer(100),  new Integer(200)},
                {"nguyenvanb",  new Integer(111),  new Integer(222)},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Friends online", "Number of friends"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addComponent(menuUserBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(navContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUserBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(navContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notiButtonActionPerformed

    private void usetModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usetModeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usetModeButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonActionPerformed

    private void dashboardNav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNav1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardNav1ActionPerformed

    private void userNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNavActionPerformed

    private void spamReportNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spamReportNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spamReportNavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUser_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUser_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUser_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUser_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUser_Friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel activityLog4;
    private javax.swing.JLabel allUser7;
    private javax.swing.JLabel allUser8;
    private javax.swing.JButton dashboardNav1;
    private javax.swing.JButton groupchatNav;
    private javax.swing.JLabel inSig4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginHistoryNav;
    private javax.swing.JPanel menuUserBar;
    private javax.swing.JPanel navContainer1;
    private javax.swing.JLabel newRegister4;
    private javax.swing.JButton notiButton;
    private javax.swing.JButton spamReportNav;
    private javax.swing.JButton userButton;
    private javax.swing.JButton userNav;
    private javax.swing.JButton usetModeButton;
    // End of variables declaration//GEN-END:variables
}
