/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wavechat.form;

/**
 *
 * @author buihi
 */
public class AdminUser extends javax.swing.JFrame {

    /**
     * Creates new form AdminUser
     */
    public AdminUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenuUser = new javax.swing.JPopupMenu();
        Lock = new javax.swing.JMenuItem();
        Unlock = new javax.swing.JMenuItem();
        updatePassword = new javax.swing.JMenuItem();
        loginHistory = new javax.swing.JMenuItem();
        friendList = new javax.swing.JMenuItem();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        notiButton = new javax.swing.JButton();
        usetModeButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        menuUserBar = new javax.swing.JPanel();
        allUser = new javax.swing.JLabel();
        newRegister = new javax.swing.JLabel();
        activityLog = new javax.swing.JLabel();
        inSig = new javax.swing.JLabel();
        allUser1 = new javax.swing.JLabel();
        functionContainer = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        navContainer1 = new javax.swing.JPanel();
        dashboardNav1 = new javax.swing.JButton();
        userNav = new javax.swing.JButton();
        groupchatNav = new javax.swing.JButton();
        spamReportNav = new javax.swing.JButton();
        loginHistoryNav = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInformationByAdmin = new javax.swing.JTable();

        Lock.setText("Lock");
        Lock.setToolTipText("");
        Lock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockActionPerformed(evt);
            }
        });
        popUpMenuUser.add(Lock);

        Unlock.setText("Unlock");
        Unlock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Unlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnlockActionPerformed(evt);
            }
        });
        popUpMenuUser.add(Unlock);

        updatePassword.setText("Update password");
        updatePassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        popUpMenuUser.add(updatePassword);

        loginHistory.setText("Login history");
        loginHistory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        popUpMenuUser.add(loginHistory);

        friendList.setText("Friend list");
        friendList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        popUpMenuUser.add(friendList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setPreferredSize(new java.awt.Dimension(178, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoSmall.png"))); // NOI18N
        jLabel2.setText("WAVE");

        notiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        notiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiButtonActionPerformed(evt);
            }
        });

        usetModeButton.setText("User mode");
        usetModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usetModeButtonActionPerformed(evt);
            }
        });

        userButton.setText("User");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                .addComponent(notiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(usetModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(usetModeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuUserBar.setBorder(new javax.swing.border.MatteBorder(null));

        allUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allUser.setText("Friends");
        allUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        allUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allUserMouseClicked(evt);
            }
        });

        newRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newRegister.setText("New register");
        newRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        activityLog.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activityLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activityLog.setText("Activity Log");
        activityLog.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        inSig.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inSig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inSig.setText("Insight");
        inSig.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        allUser1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        allUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allUser1.setText("All User");
        allUser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout menuUserBarLayout = new javax.swing.GroupLayout(menuUserBar);
        menuUserBar.setLayout(menuUserBarLayout);
        menuUserBarLayout.setHorizontalGroup(
            menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUserBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(allUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allUser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activityLog, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inSig, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuUserBarLayout.setVerticalGroup(
            menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUserBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuUserBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSig)
                    .addComponent(activityLog)
                    .addComponent(newRegister)
                    .addComponent(allUser)
                    .addComponent(allUser1))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        add.setText("Add");

        javax.swing.GroupLayout functionContainerLayout = new javax.swing.GroupLayout(functionContainer);
        functionContainer.setLayout(functionContainerLayout);
        functionContainerLayout.setHorizontalGroup(
            functionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        functionContainerLayout.setVerticalGroup(
            functionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionContainerLayout.createSequentialGroup()
                .addGroup(functionContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        navContainer1.setBorder(new javax.swing.border.MatteBorder(null));
        navContainer1.setPreferredSize(new java.awt.Dimension(188, 496));

        dashboardNav1.setBackground(new java.awt.Color(26, 41, 128));
        dashboardNav1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboardNav1.setForeground(new java.awt.Color(255, 255, 255));
        dashboardNav1.setText("Dashboard");
        dashboardNav1.setPreferredSize(new java.awt.Dimension(165, 40));
        dashboardNav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNav1ActionPerformed(evt);
            }
        });

        userNav.setBackground(new java.awt.Color(26, 41, 128));
        userNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userNav.setForeground(new java.awt.Color(255, 255, 255));
        userNav.setText("User");
        userNav.setMaximumSize(new java.awt.Dimension(165, 40));
        userNav.setMinimumSize(new java.awt.Dimension(165, 40));
        userNav.setPreferredSize(new java.awt.Dimension(165, 40));
        userNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNavActionPerformed(evt);
            }
        });

        groupchatNav.setBackground(new java.awt.Color(26, 41, 128));
        groupchatNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        groupchatNav.setForeground(new java.awt.Color(255, 255, 255));
        groupchatNav.setText("Login History");
        groupchatNav.setPreferredSize(new java.awt.Dimension(165, 40));

        spamReportNav.setBackground(new java.awt.Color(26, 41, 128));
        spamReportNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spamReportNav.setForeground(new java.awt.Color(255, 255, 255));
        spamReportNav.setText("Spam Report");
        spamReportNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spamReportNavActionPerformed(evt);
            }
        });

        loginHistoryNav.setBackground(new java.awt.Color(26, 41, 128));
        loginHistoryNav.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginHistoryNav.setForeground(new java.awt.Color(255, 255, 255));
        loginHistoryNav.setText("Group Chat");

        javax.swing.GroupLayout navContainer1Layout = new javax.swing.GroupLayout(navContainer1);
        navContainer1.setLayout(navContainer1Layout);
        navContainer1Layout.setHorizontalGroup(
            navContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardNav1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(userNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(groupchatNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginHistoryNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spamReportNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navContainer1Layout.setVerticalGroup(
            navContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navContainer1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(dashboardNav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupchatNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginHistoryNav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spamReportNav, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userInformationByAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userInformationByAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"buihien", "Bùi Hiền", "Tp hcm", "19/02/2004", "Nam", "abc@gmail,com", "Online", "Unlock"},
                {"buihien", "Bùi Hiền", "Tp hcm", "19/02/2004", "Nam", "abc@gmail,com", "Online", "Unlock"},
                {"buihien", "Bùi Hiền", "Tp hcm", "19/02/2004", "Nam", "abc@gmail,com", "Online", "Unlock"},
                {"phuvinh", "Phú Vinh", "Tp hcm", "12/03/2004", "Nam", "abc@gmail,com", "Offline", "Lock"},
                {"phuvinh", "Phú Vinh", "Tp hcm", "12/03/2004", "Nam", "abc@gmail,com", "Offline", "Lock"},
                {"phuvinh", "Phú Vinh", "Tp hcm", "12/03/2004", "Nam", "abc@gmail,com", "Offline", "Lock"},
                {"phuvinh", "Phú Vinh", "Tp hcm", "12/03/2004", "Nam", "abc@gmail,com", "Offline", "Unlock"},
                {"", null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Full name", "Address", "Birth", "Gender", "Mail", "Status", "Lock/Unlock"
            }
        ));
        userInformationByAdmin.setComponentPopupMenu(popUpMenuUser);
        userInformationByAdmin.setShowGrid(false);
        jScrollPane1.setViewportView(userInformationByAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuUserBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(navContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(functionContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUserBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(functionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                    .addComponent(navContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notiButtonActionPerformed

    private void usetModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usetModeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usetModeButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonActionPerformed

    private void dashboardNav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNav1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardNav1ActionPerformed

    private void userNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNavActionPerformed

    private void spamReportNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spamReportNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spamReportNavActionPerformed

    private void LockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LockActionPerformed

    private void UnlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnlockActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void allUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allUserMouseClicked
        // TODO add your handling code here:
        // Tạo đối tượng của AdminUser_Friends
        AdminUser_Friends adminUserFriends = new AdminUser_Friends();
    
        // Hiển thị giao diện AdminUser_Friends
        adminUserFriends.setVisible(true);
    }//GEN-LAST:event_allUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JMenuItem Lock;
    private javax.swing.JMenuItem Unlock;
    private javax.swing.JLabel activityLog;
    private javax.swing.JButton add;
    private javax.swing.JLabel allUser;
    private javax.swing.JLabel allUser1;
    private javax.swing.JButton dashboardNav1;
    private javax.swing.JButton delete;
    private javax.swing.JMenuItem friendList;
    private javax.swing.JPanel functionContainer;
    private javax.swing.JButton groupchatNav;
    private javax.swing.JLabel inSig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem loginHistory;
    private javax.swing.JButton loginHistoryNav;
    private javax.swing.JPanel menuUserBar;
    private javax.swing.JPanel navContainer1;
    private javax.swing.JLabel newRegister;
    private javax.swing.JButton notiButton;
    private javax.swing.JPopupMenu popUpMenuUser;
    private javax.swing.JButton spamReportNav;
    private javax.swing.JMenuItem updatePassword;
    private javax.swing.JButton userButton;
    private javax.swing.JTable userInformationByAdmin;
    private javax.swing.JButton userNav;
    private javax.swing.JButton usetModeButton;
    // End of variables declaration//GEN-END:variables
}
