package com.wavechat.form;

import com.wavechat.contentPanel.AuthenticationForgotPassPanel;
import com.wavechat.contentPanel.AuthenticationLoginPanel;
import com.wavechat.contentPanel.AuthenticationRegisterPanel;
import com.wavechat.contentPanel.AuthenticationThankYouPanel;

public class AuthenticationMain extends javax.swing.JFrame {

    AuthenticationLoginPanel loginPanel = new AuthenticationLoginPanel(this);
    AuthenticationRegisterPanel registerPanel = new AuthenticationRegisterPanel(this);
    AuthenticationForgotPassPanel forgotPassPanel = new AuthenticationForgotPassPanel(this);
    AuthenticationThankYouPanel thankYouPanel = new AuthenticationThankYouPanel(this);
    
    public AuthenticationMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        contentContainer.add(loginPanel);
        contentContainer.add(registerPanel);
        contentContainer.add(forgotPassPanel);
        contentContainer.add(thankYouPanel);
        
        loginPanel.setVisible(true);        
        registerPanel.setVisible(false);
        forgotPassPanel.setVisible(false);
        thankYouPanel.setVisible(false);
    }
    
    public void showLoginPanel() {
        loginPanel.setVisible(true);        
        registerPanel.setVisible(false);
        forgotPassPanel.setVisible(false);
        thankYouPanel.setVisible(false);
    }

    public void showRegisterPanel() {
        loginPanel.setVisible(false);        
        registerPanel.setVisible(true);
        forgotPassPanel.setVisible(false);
        thankYouPanel.setVisible(false);
    }
    
    public void showForgotPassPanel() {
        loginPanel.setVisible(false);        
        registerPanel.setVisible(false);
        forgotPassPanel.setVisible(true);
        thankYouPanel.setVisible(false);
    }
    
    public void showThankYouPanel() {
        loginPanel.setVisible(false);        
        registerPanel.setVisible(false);
        forgotPassPanel.setVisible(false);
        thankYouPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentContainer = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wave");
        setPreferredSize(new java.awt.Dimension(500, 630));
        setResizable(false);

        contentContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane contentContainer;
    // End of variables declaration//GEN-END:variables
}
