package com.wavechat.form;

import com.wavechat.Navigation;
import com.wavechat.bus.UserBUS;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    // Hàm xử lí login
    private void handleLogin() {
        String emailOrUsername = emailOrUsernameInput.getText(); 
        String password = passwordInput.getText(); 

        UserBUS userBUS = new UserBUS();

        // Kiểm tra xem người dùng có nhập đủ thông tin không
        if (emailOrUsername.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill full login information", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Kiểm tra nếu người dùng nhập vào email
        if (userBUS.isEmail(emailOrUsername)) {
            // Nếu là email, kiểm tra trong db
            if (userBUS.isEmailExist(emailOrUsername)) {
                // Kiểm tra password
                if (userBUS.validateUser(emailOrUsername, password)) {
                    boolean isAdmin = userBUS.isAdmin(emailOrUsername);
                    if (isAdmin) {
                        // Chuyển tới trang Admin
                        Navigation navigation = new Navigation();
                        navigation.navigateToAdminHome(this);
                    } else {
                        // Chuyển tới trang User
                        Navigation navigation = new Navigation();
                        navigation.navigateToUserHome(this);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "Wrong password.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 
            else {
                JOptionPane.showMessageDialog(this, "Wrong login information.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
        else  {
            // Nếu là username, kiểm tra trong db
            if (userBUS.isUserNameExist(emailOrUsername)) {
                // Kiểm tra password
                if (userBUS.validateUser(emailOrUsername, password)) {
                    boolean isAdmin = userBUS.isAdmin(emailOrUsername);
                    if (isAdmin) {
                        // Chuyển tới trang Admin
                        Navigation navigation = new Navigation();
                        navigation.navigateToAdminHome(this);
                        
                    } else {
                        // Chuyển tới trang User
                        Navigation navigation = new Navigation();
                        navigation.navigateToUserHome(this);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "Wrong password.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 
            else {
                JOptionPane.showMessageDialog(this, "Wrong login information.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginPanel = new java.awt.Panel();
        loginContainer = new java.awt.Panel();
        logo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        emailOrUsernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        donothaveacc = new javax.swing.JLabel();
        navRegisterButton = new javax.swing.JButton();
        forgotpassButton = new javax.swing.JPanel();
        forgotPassButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wave - Login");
        setBackground(new java.awt.Color(246, 246, 246));

        loginPanel.setBackground(new java.awt.Color(246, 246, 246));
        loginPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        loginContainer.setBackground(new java.awt.Color(246, 246, 246));
        java.awt.GridBagLayout loginContainerLayout = new java.awt.GridBagLayout();
        loginContainerLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        loginContainerLayout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        loginContainer.setLayout(loginContainerLayout);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        loginContainer.add(logo, gridBagConstraints);

        login.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        login.setText("Log in");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginContainer.add(login, gridBagConstraints);

        slogan.setText("Join to connect and share your waves.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        loginContainer.add(slogan, gridBagConstraints);

        emailOrUsernameInput.setBackground(new java.awt.Color(246, 246, 246));
        emailOrUsernameInput.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        emailOrUsernameInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email address or username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        emailOrUsernameInput.setPreferredSize(new java.awt.Dimension(294, 35));
        emailOrUsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailOrUsernameInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginContainer.add(emailOrUsernameInput, gridBagConstraints);

        passwordInput.setBackground(new java.awt.Color(246, 246, 246));
        passwordInput.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        passwordInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        passwordInput.setPreferredSize(new java.awt.Dimension(294, 35));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginContainer.add(passwordInput, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(26, 41, 128));
        loginButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Log in");
        loginButton.setPreferredSize(new java.awt.Dimension(294, 35));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 35, 0);
        loginContainer.add(loginButton, gridBagConstraints);

        donothaveacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        donothaveacc.setText("Don't have an account?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        loginContainer.add(donothaveacc, gridBagConstraints);

        navRegisterButton.setBackground(new java.awt.Color(26, 41, 128));
        navRegisterButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        navRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        navRegisterButton.setText("Register");
        navRegisterButton.setPreferredSize(new java.awt.Dimension(100, 35));
        navRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navRegisterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginContainer.add(navRegisterButton, gridBagConstraints);

        forgotpassButton.setBackground(new java.awt.Color(246, 246, 246));
        forgotpassButton.setPreferredSize(new java.awt.Dimension(200, 22));
        forgotpassButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        forgotPassButton.setBackground(new java.awt.Color(246, 246, 246));
        forgotPassButton.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        forgotPassButton.setText("Forgot password?");
        forgotPassButton.setBorder(null);
        forgotPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassButtonActionPerformed(evt);
            }
        });
        forgotpassButton.add(forgotPassButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        loginContainer.add(forgotpassButton, gridBagConstraints);

        loginPanel.add(loginContainer, new java.awt.GridBagConstraints());

        getContentPane().add(loginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navRegisterButtonActionPerformed
        // Navigate qua register
        Navigation navigation = new Navigation();
        navigation.navigateToRegister(this);
    }//GEN-LAST:event_navRegisterButtonActionPerformed

    private void emailOrUsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailOrUsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailOrUsernameInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        handleLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void forgotPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassButtonActionPerformed
        // Navigate qua reset pass
        this.setVisible(false); 
        ForgotPassword forgotPasswordFrame = new ForgotPassword(); 
        forgotPasswordFrame.setVisible(true); 
    }//GEN-LAST:event_forgotPassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donothaveacc;
    private javax.swing.JTextField emailOrUsernameInput;
    private javax.swing.JButton forgotPassButton;
    private javax.swing.JPanel forgotpassButton;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginButton;
    private java.awt.Panel loginContainer;
    private java.awt.Panel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton navRegisterButton;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
