/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wavechat.form;

/**
 *
 * @author LENOVO
 */
public class RegisterSuccessful extends javax.swing.JFrame {

    /**
     * Creates new form ThankYouForRegister
     */
    public RegisterSuccessful() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        thankyou2 = new java.awt.Panel();
        thankyouContainer2 = new java.awt.Panel();
        logo2 = new javax.swing.JLabel();
        login2 = new javax.swing.JLabel();
        description2 = new javax.swing.JPanel();
        jTextArea7 = new javax.swing.JTextArea();
        checkemail2 = new javax.swing.JPanel();
        jTextArea9 = new javax.swing.JTextArea();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wave - Register Successful");

        thankyou2.setBackground(new java.awt.Color(246, 246, 246));
        thankyou2.setPreferredSize(new java.awt.Dimension(500, 600));
        thankyou2.setLayout(new java.awt.GridBagLayout());

        thankyouContainer2.setBackground(new java.awt.Color(246, 246, 246));
        thankyouContainer2.setLayout(new java.awt.GridBagLayout());

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        thankyouContainer2.add(logo2, gridBagConstraints);

        login2.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        login2.setText("Successful");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        thankyouContainer2.add(login2, gridBagConstraints);

        description2.setBackground(new java.awt.Color(246, 246, 246));
        description2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jTextArea7.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea7.setColumns(5);
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(2);
        jTextArea7.setTabSize(1);
        jTextArea7.setText("We've sent your account password to your email address. Please check your inbox to retrieve it.");
        jTextArea7.setWrapStyleWord(true);
        jTextArea7.setAutoscrolls(false);
        jTextArea7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea7.setEnabled(false);
        jTextArea7.setPreferredSize(new java.awt.Dimension(280, 52));
        description2.add(jTextArea7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        thankyouContainer2.add(description2, gridBagConstraints);

        checkemail2.setBackground(new java.awt.Color(246, 246, 246));
        checkemail2.setPreferredSize(new java.awt.Dimension(280, 36));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout3.setAlignOnBaseline(true);
        checkemail2.setLayout(flowLayout3);

        jTextArea9.setBackground(new java.awt.Color(246, 246, 246));
        jTextArea9.setColumns(3);
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(2);
        jTextArea9.setTabSize(1);
        jTextArea9.setText("Haven’t received the email? Please check on Spam or Promotions.");
        jTextArea9.setWrapStyleWord(true);
        jTextArea9.setAutoscrolls(false);
        jTextArea9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea9.setEnabled(false);
        jTextArea9.setPreferredSize(new java.awt.Dimension(250, 52));
        checkemail2.add(jTextArea9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        thankyouContainer2.add(checkemail2, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(26, 41, 128));
        loginButton.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Back to log in");
        loginButton.setPreferredSize(new java.awt.Dimension(260, 35));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 35, 0);
        thankyouContainer2.add(loginButton, gridBagConstraints);

        thankyou2.add(thankyouContainer2, new java.awt.GridBagConstraints());

        getContentPane().add(thankyou2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterSuccessful.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterSuccessful().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel checkemail2;
    private javax.swing.JPanel description2;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel login2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo2;
    private java.awt.Panel thankyou2;
    private java.awt.Panel thankyouContainer2;
    // End of variables declaration//GEN-END:variables
}
